We are the 27-07-2022 15:21:42
imports done
test passed, 258735 parameters
args:  Namespace(exp_name='test_PDM', exp_index=0, model='PDM', batch_size=100, optimizer='Adam', num_epochs=50, lr=1e-05, weight_decay=1e-06, step_size=20, gamma=0.1, stride=6, n_channel=20, kernel_size=613, dilation=1, pdm_factor=10, predict=False, log_interval=200, load_checkpoint=None, nosavemodel=False, COLAB=False, no_validation=False, fe=8000, n_mels=50, win_length=240, hop_length=80, n_fft=240)
setting up exp: test_PDM
Using : cuda
Compute Canada detected, root set to /localscratch/yoogo.30471437.0
Training mode
training loader set up, size 84843
validation loader set up, size 9981
training/validation sets finished in  0:00:30.148365
saving tensorboard in runs/test_PDM
PDM model setup
Launching exp: test_PDM index 0
  0%|          | 0/50 [00:00<?, ?it/s]terminate called after throwing an instance of 'c10::CUDAError'
  what():  CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Exception raised from memcpy_and_sync at /tmp/coulombc/pytorch_build_2021-11-10_08-09-16/avx2/python3.9/pytorch/c10/cuda/CUDAFunctions.h:75 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x55 (0x2b9072f73905 in /home/yoogo/venv/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x132fed5 (0x2b9057f5ded5 in /home/yoogo/venv/lib/python3.9/site-packages/torch/lib/libtorch_cuda.so)
frame #2: at::native::_local_scalar_dense_cuda(at::Tensor const&) + 0x30 (0x2b9057f5e5e0 in /home/yoogo/venv/lib/python3.9/site-packages/torch/lib/libtorch_cuda.so)
frame #3: <unknown function> + 0x315e7cd (0x2b9059d8c7cd in /home/yoogo/venv/lib/python3.9/site-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0x315e82d (0x2b9059d8c82d in /home/yoogo/venv/lib/python3.9/site-packages/torch/lib/libtorch_cuda.so)
frame #5: at::_ops::_local_scalar_dense::redispatch(c10::DispatchKeySet, at::Tensor const&) + 0xa5 (0x2b904e23c615 in /home/yoogo/venv/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)

/var/spool/slurmd/job30471437/slurm_script: line 19: 39464 Aborted                 (core dumped) python run_array_PDM.py $SLURM_ARRAY_TASK_ID
